name: shop_rent_flutter
description: A modern Shop Rent Management application.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Networking & Data
  http: ^1.2.0
  intl: ^0.19.0
  # State Management
  provider: ^6.1.1

  # UI & Design
  google_fonts: ^6.1.0

  # Utilities
  excel: ^4.0.0
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  open_file: ^3.3.2

  # Features
  pdf: ^3.10.0
  printing: ^5.11.0
  url_launcher: ^6.2.0
  share_plus: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/
